purbeurre/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('search/', views.search, name='search'),
    path('contacts/', views.contacts, name='contacts'),
    path('legal/', views.legal, name='legal'),
    path('<int:id_product>', views.detail, name='product_detail'),
]

purbeurre_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from users import views

urlpatterns = [
    # home route
    path("", views.index, name="index"),
    url(r'^purbeurre/', include(('purbeurre.urls', 'purbeurre'), namespace='purbeurre')),
    path('users/', include('users.urls', namespace="users")),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"

urlpatterns = [
    path('register/', views.sign_up, name='sign_up'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('account/', views.account, name='account'),
    path('saved/', views.saved, name='saved')
]

purbeurre/models.py
from django.db import models
from users.models import User
# from django.contrib.auth.models import User


# Create your models here.

class Categories(models.Model):
    """Model for creating OpenFoodFacts categories"""
    category_name = models.CharField(max_length=500, unique=True)

    def __str__(self):
        return self.category_name


class Products(models.Model):
    """Model for creating OpenFoodFacts products"""
    id_product = models.BigIntegerField(primary_key=True)
    product_name = models.CharField(max_length=255)
    url = models.URLField()
    img = models.URLField()
    fat = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    saturated_fat = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    salt = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    sugar = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    nutrition_score = models.CharField(max_length=1, null=True)
    category = models.ForeignKey("Categories", on_delete=models.CASCADE)

    def __str__(self):
        return str({
            "id_product": self.id_product,
            "product_name": self.product_name,
            "url": self.url,
            "image": self.img,
            "nutrition_score": self.nutrition_score,
            "category": self.category
        })


class Substitutes(models.Model):
    """Table association between products and user to save a chosen substitute product for a specific user"""
    origin = models.ForeignKey(Products, related_name='origin', on_delete=models.CASCADE)
    replacement = models.ForeignKey(Products, related_name='replacement', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user', on_delete=models.CASCADE, null=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["origin", "replacement", "user"],
                name="unique_user_favoris",
            )
        ]

    def __str__(self):
        return str({
            "origin": self.origin,
            "replacement": self.replacement,
            "user": self.user
        })

purbeurre/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from users.models import User


class UserRegisterForm(UserCreationForm):
    """Customize register formulaire"""

    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "example@email.com",
            }
        ),
    )
    username = forms.CharField(
        label="Nom de l'utilisateur",
        widget=forms.TextInput(
            attrs={
                "placeholder": "nom d'utilisateur",
            }
        ),
    )

    password1 = forms.CharField(
        label="Mot de passe",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Mot de passe",
                "type": "password",
            }
        ),
    )

    password2 = forms.CharField(
        label="Confirmation de votre de passe",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Confirmation",
                "type": "password",
            }
        ),
    )

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

purbeurre/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Products, Substitutes
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from users.models import User
from django.http import Http404


# Create your views here.

def index(request):
    context = {
        'page_title': 'Accueil'
    }
    return render(request, 'purbeurre/index.html')


def search(request):
    # query of the search product
    query = request.GET.get('query')

    # If query matches with product_name
    query_prod = Products.objects.filter(product_name__contains=query).first()

    # Check if the given string is contained in the value in database filed, query is not sensitive to case.
    if not query_prod:
        query_prod = Products.objects.filter(product_name__icontains=query).first()

    if not query_prod:
        # raise Http404("Poll does not exist")
        return redirect('purbeurre/404.html')
    else:
        products_list = Products.objects.filter(category=query_prod.category).filter(
            nutrition_score__lte=query_prod.nutrition_score).order_by('nutrition_score')
        # If user login is True
        if request.user.is_authenticated:
            # Remove products that are  already in the user's list
            for product in products_list:
                listed = Substitutes.objects.filter(
                    origin=query_prod.id_product,
                    replacement=product.id_product,
                    user=request.user
                )
                if listed:
                    products_list = products_list.exclude(pk=product.id_product)

    # If user wants to save a product
    if request.user.is_authenticated and request.method == 'POST':
        # product  searched
        origin = request.POST.get('origin')
        # get the replacement 
        replacement = request.POST.get('replacement')
        origin = Products.objects.get(pk=origin)
        replacement = Products.objects.get(pk=replacement)

        # Place the searched product and its alternative in the user's list
        Substitutes.objects.create(
            origin=origin,
            replacement=replacement,
            user=request.user
        )
        # exclude saved items from search results page
        products_list = products_list.exclude(pk=replacement.id_product)

    # pagination 9 products per page
    paginator = Paginator(products_list, 9)
    page = request.GET.get('page')

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    # Get the index of the current page
    page_index = products.number - 1
    # This value is maximum index of your pages, so the last page - 1
    max_index = len(paginator.page_range)
    # You want a range of 10, so lets calculate where to slice the list
    start_index = page_index - 10 if page_index >= 10 else 0
    end_index = page_index + 10 if page_index <= max_index - 10 else max_index
    # Get our new page range. In the latest versions of Django page_range returns 
    # an iterator. Thus pass it to list, to make our slice possible again.
    page_range = list(paginator.page_range)[start_index:end_index]

    context = {
        'products': products,
        'paginate': True,
        'query': query,
        'title': query_prod.product_name,
        'category': query_prod.category,
        'img': query_prod.img,
        'query_prod': query_prod.id_product,
        'page_range': page_range,

    }

    return render(request, 'purbeurre/search.html', context)


def detail(request, id_product):
    """
    detail information of each product
    """
    product = get_object_or_404(Products, pk=id_product)

    context = {
        "img": product.img,
        'product': product,
        "product_name": product.product_name
    }

    return render(request, 'purbeurre/product_detail.html', context)


# Contacts
def contacts(request):
    """
    contact page for the application
    """
    context = {
        "page_title": 'Nous contacter'
    }
    return render(request, 'purbeurre/contacts.html', context)


def legal(request):
    """
    legal page for the application
    """
    # Render
    context = {
        "title": "Mentions légales",
        "page_title": "Mentions légales"
    }
    return render(request, 'purbeurre/legal.html', context)

templates/purbeurre/account.html
{% extends 'purbeurre/base.html'%}
{% load static %}

{% block title%}{{ page_title }}{% endblock %}

{% block content %}

<!-- {% include 'purbeurre/header.html' with title=title img=img %}  -->

<section style="background-image: url('{{img}}');" class="page-section bg-dark text-white">
    <div class="col-lg-10 mx-auto text-center">
      <div class="account-msg-box">
        <h1 class="text-uppercase favorite-msg"><span class="account-msg-txt">Ahoy !</span></h1>
        <p> Bienvenue sur votre espace personnel</p>
      </div>
  </section>

  <section class="page-section  text-white">
    <div class="text-center useravatar">
        <img src="{% static 'purbeurre/img/default_user_100x100.png' %}">
        <p class='userName'>{{user.username}} </p>
        <br>
        <!-- <p class='userName'>Email: {{user.email}}</p> -->
        <button  class='emailButton'><i class="material-icons" style="font-size:36px">mail</i> <a href = "mailto: abc@example.com">{{user.email}}</a></button> 
    </div>
    <br>
    <br>
    <div class="container">
        <div class="text-center">
               <a class="btn btn-primary" href="{% url 'users:saved'%}" role="button">Mes aliments</a>
               <a class="btn btn-primary" href="{% url 'users:logout'%}" role="button">Déconnexion</a>
    </div>
</div>

</section>


{% endblock content %}

templates/purbeurre/base.html
<!DOCTYPE html>
<html lang="fr">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    {% load static %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'purbeurre/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Fonts  -->
    <link href="{% static 'purbeurre/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link href="http://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">
    <!-- Plugin CSS -->
    <link href="{% static 'purbeurre/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Custom styles -->
    <link href="{% static 'purbeurre/css/creative.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Favicon -->
    <link rel="icon" type="image/png" href="{% static 'purbeurre/img/purbeurre_favicon.png' %}"/>

  </head>

    <div class="site-content">
    <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
      <div class="container">
          <a href="/"><img src="{% static 'purbeurre/img/logo_pur_beurre.png' %}" width="50px"></a>
          <a class="navbar-brand js-scroll-trigger" href="/"> &nbsp; Pur Beurre</a>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse"  id="navbarResponsive">
            <ul class="navbar-nav ml-auto my-2 my-lg-0" style="position:absolute; right:80px;">
              <li class="nav-item">
                <form method="get" action="{% url 'purbeurre:search' %}" >
                  <input name="query" placeholder="chercher..">
                  <button ><i class="fa fa-search fa-2x " aria-hidden="true"></i></button>
                </form>
              </li>
              <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link js-scroll-trigger" href="{% url 'users:account' %}"><i class="fa fa-user fa-2x" aria-hidden="true"></i></a> 
                {% else %}
                <a class="nav-link js-scroll-trigger" href="{% url 'users:login' %}"><i class="fa fa-user fa-2x" aria-hidden="true"></i></a> 
                {% endif %}
             </li>
             {% if user.is_authenticated %}
           <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'users:saved' %}">
                  <img src="{% static 'purbeurre/img/logo_carotte.png' %}" width="45px" height="45px">
              </a>
            </li>
              
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'users:logout' %}"><i class="fa fa-sign-out fa-2x" aria-hidden="true"></i></a>
            </li>   
            {% endif %}
            </ul> 
          </div>
      </div>
  </nav>

  {% block content %}{% endblock content %}
    
  <!-- Footer-->
    <footer class="bg-light py-5">
      <div class="container">
      <div class="small text-right text-muted"><a href="{% url 'purbeurre:contacts'%}" class="ml-5 text-muted">Contacts</a></div>
      <div class="small text-left text-muted"><a href="{% url 'purbeurre:legal'%}" class="ml-5 text-muted">Mentions légales</a></div>
      </div>
    </footer>
    <!-- Bootstrap core JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Plugin JavaScript -->
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
    <!-- Custom scripts for this template -->
    
    <script src="{% static 'purbeurre/js/scripts.js' %}"></script>
  </body>

</html>

templates/purbeurre/contact.html
<section class="page-section" id="contact">
  <div class="container">
      <div class="row justify-content-center">
          <div class="col-lg-8 text-center">
              <h2 class="mt-0">Contactez-nous !</h2>
              <hr class="divider my-4" />
              <p class="text-muted mb-5">Nous serons ravis de vous répondre ! !</p>
          </div>
      </div>
      <div class="row">
          <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
            <i class="fa fa-phone fa-3x mb-3 sr-contact"></i>
              <div>+33 (555) 123-4567</div>
          </div>
          <div class="col-lg-4 mr-auto text-center">
            <i class="fa fa-envelope-o fa-3x mb-3 sr-contact"></i>
              <!-- Make sure to change the email address in BOTH the anchor text and the link target below!-->
              <a class="d-block" href="mailto:your-email@your-domain.com">mail@purbeurre.com</a>
          </div>
      </div>
  </div>
</section>

templates/purbeurre/contacts.html
{% extends 'purbeurre/base.html'%}

{% block title%}{{ page_title }}{% endblock %}

{% block content %}

{% include 'purbeurre/header.html' with title=title img=img %} 


 {% include 'purbeurre/contact.html' %}


{% endblock content %}

templates/purbeurre/header.html
<section  class="page-section bg-dark text-white">
  <div class="col-lg-10 mx-auto text-center">
    <h3 class="section-heading text-white">{{title.upper}}</h3>
    </div>
</section>

 

templates/purbeurre/index.html
{% extends 'purbeurre/base.html'  %}

{% load static %}

{% block title%}{{ page_title }}{% endblock %}

{% block content %}

<header class="masthead text-center text-white d-flex">
  <div class="container my-auto">
    <div class="row">
      <div class="col-lg-10 mx-auto">
        <h1 class="text-white">
          Du gras, oui, mais de qualité !
        </h1>
      </div>
      <div class="col-lg-8 mx-auto">
        <h2 class="mb-5 text-white">Trouvez un produit de substitution pour ceux que vous consommez tous les jours</h2>
        <form action="{% url 'purbeurre:search' %}" method="get" accept-charset="utf-8">
          <input type="text" name="query" class="form-control" placeholder="Produit à susbstituer »..." name="query" id="input_product">
          <button class="btn mt-4 btn-primary" type="submit" id= "submit_button"> Chercher </button>
        </form>
      </div>
    </div>
  </div>
  
</header>

<!-- Services-->
<section class="page-section bg-dark text-white" id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading"> Colette et Rémy</h2>
        <hr class="light my-4">
      </div>
    </div>
  </div>
  <div class="container">
    <h4 class="col-lg-12 col-md-6 text-center"> Le mot des fondateurs</h4>
    <div class="row">
      <div class="col-lg-6 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <img src="{% static 'purbeurre/img/colette.png' %}" height="150" alt="Photo de Colette" >
          <h3 class="mb-3">Colette</h3>
          <p class="text-faded mb-4 text-justify"> "Nous aimons tous manger, surtout en France ! 
            Personnellement, une baguette fraîche, du bon fromage de chèvre et un bon vin rouge me suffisent amplement. 
            Comme tout le monde, je fais mes courses au supermarché. 
            Mais petit à petit je me suis rendue compte, surtout lorsque nous avons ouvert le restaurant, 
            que je pouvais remplacer les produits aseptisés que j'avais l'habitude d'acheter par de bons produits du terroir. Et souvent pour le même prix !" </p>
        </div>
      </div>
      <div class="col-lg-6 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <img src="{% static 'purbeurre/img/remy.png' %}" height="150" alt="Photo de Rémy">
          <h3 class="mb-3">Rémy</h3>
          <p class="text-faded mb-4 text-justify"> "Pour ma part je me rendais déjà dans bien des magasins car j'aime beaucoup me balader, surtout dans les caves et les cuisines. 
            Je connaissais par coeur le contenu des boutiques bio (dont je raffole) ainsi que les ingrédients de tous les aliments vendus. 
            Lorsque Colette m'a demandé si elle pouvait remplacer son Nutella matinal par un aliment plus sain, je savais tout de suite où le trouver. L'idée de Pur Beurre était née !"</p>
        </div>
      </div>
    </div>
  </div>
</section>
<!--  end of Services-->


{% include 'purbeurre/contact.html' %}


{% endblock %}

templates/purbeurre/saved.html
{% extends 'purbeurre/base.html' %}

{% block title%}{{ page_title }}{% endblock %}
{% load static %}
{% block content %}

{% include 'purbeurre/header.html' with title=title  %}

{% if products_saved|length_is:"0" %}
<section class="page-section bg-dark text-white">
    <div class="container text-center">
    <h2>Vous n'avez pas encore de produits sauvegardés</h2><br>
    <p>Cherchez un produit plus sain sur notre site web et sauvegardez-le dans votre espace personnel pour le retrouver plus facilement la prochaine fois !.</p>
    </div>
</section>

{% else %}

<section>
     <div class="container-fluid">
        <div class="row">
          {% for product in products_saved %}
          <!-- display infos about saved product -->
            <div class="col-xl-4 col-lg-6 col-md-6 col-xs-1 text-center border product-block">
            
            {% if product.replacement.nutrition_score == "a" %}
              <div class="nutri-grade"><span class="badge nutri-a text-white">{{ product.replacement.nutrition_score.upper }}</span></div>
            {% elif product.replacement.nutrition_score == "b" %}
              <div class="nutri-grade"><span class="badge nutri-b text-white">{{ product.replacement.nutrition_score.upper }}</span></div>
            {% elif product.replacement.nutrition_score == "c" %}
              <div class="nutri-grade"><span class="badge nutri-c text-dark">{{ product.replacement.nutrition_score.upper }}</span></div>
            {% elif product.replacement.nutrition_score == "d" %}
              <div class="nutri-grade"><span class="badge nutri-d text-white">{{ product.replacement.nutrition_score.upper }}</span></div>
            {% elif product.replacement.nutrition_score == "e" %}
              <div class="nutri-grade"><span class="badge nutri-e text-white">{{ product.replacement.nutrition_score.upper }}</span></div>
            {% endif %}

            <div class="container vbottom p-3">
                <a href="{% url 'purbeurre:product_detail' id_product=product.replacement.id_product %}">
                    {% if product.replacement.img is none %}
                      <img class="img-responsive" src="{% static 'purbeurre/img/logo_pur_beurre.png' %}" alt="{{ product.replacement.product_name }}">
                    {% else %}
                      <img class="img-responsive" src="{{ product.replacement.img }}" alt="{{ product.replacement.product_name }}">
                    {% endif %}
                  </a>
                  <h4><a href="{% url 'purbeurre:product_detail' id_product=product.replacement.id_product %}">{{ product.replacement.product_name}}</a></h4>
                  
                  <div class="favs mt-2">
                    <!-- pass product_id to the url, to use it in the view and push it to db -->
                    <!-- {% if user.is_authenticated %} -->
                    <form method="post">
                      {% csrf_token %}         
                      <input type="hidden" name="origin" value="{{product.origin.id_product}}"/>
                      <input type="hidden" name="replacement" value="{{product.replacement.id_product}}"/>
                      <button class="btn btn-danger"><i class="fa fa-minus-square" aria-hidden="true">&nbsp; Retirer des favoris</i></button>
                    </form>
                    <!-- {% endif %} -->
                  </div>
            </div>

        </div>
        {% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div>{% endif %}
        {% endfor %}
    <!-- !!end display infos about saved product -->
    </div>
  </div>


  {% if paginate %}
  <div class="clearfix"></div>
  <div class="container center my-4">
      <nav aria-label="">
          <ul class="pagination pagination-sm flex-wrap justify-content-center" style="text-overflow: ellipsis;">
            {% if products_saved.has_previous %}
                <li class="page-item"><a class="page-link" href="?query={{ query }}&page={{ products.previous_page_number }}" aria-label='Précédent'>&laquo;</a></li>
            {% endif %}

            {% for page in products_saved.paginator.page_range %}
              {% if page %}
                {% ifequal page products_saved.number %}
                  <li class="page-item active">
                    <span class="page-link">{{ page }}</span>
                  </li>
                {% else %}
                  <li class="page-item">
                    <a href="?query={{ query }}&page={{ page }}" class="page-link">{{ page }}</a>
                  </li>
                {% endifequal %}
              {% else %}
                <li class="page-item disabled"><span class="page-link">. . .</span></li>
              {% endif %}
              {% endfor %}
              {% if products_saved.has_next %}
                <li class="page-item"><a class="page-link" href="?query={{ query }}&page={{ products.next_page_number }}" aria-label='suivant'>&raquo;</a></li>
            {% endif %}
          </ul>
      </nav>
  </div>

  {% endif %}

</div>
{% endif %}
</section>
{% endblock content %}

templates/purbeurre/search.html
{% extends 'purbeurre/base.html' %}
{% block title%}{{ page_title }}{% endblock %}


{% load static %}

{% block content %}

<section  class="page-section bg-dark text-white">
    <div class="col-lg-10 mx-auto text-center">
      <h3 class="section-heading text-white">{{title}}</h3>
      </div>
  </section>


{% if products|length_is:"0" %}
<section >
    <div class="container text-center">
          <h2>Mince, aucun produit ne correspond à cette recherche. Cherchez à nouveau !</h2><br>
      </div>
</section>

{% else %}
<section>
  <div class='container text-center mb-5'>
    <h2> Suggestion de produits
    <hr class='light my-4'> 
  </h2>

  <div class="container-fluid">
    <div class="row">
      {% for product in products %}
      <!-- display infos about product -->
        <div class="col-xl-4 col-lg-6 col-md-6 col-xs-1 text-center border product-block">
        
        {% if product.nutrition_score == "a" %}
          <div class="nutri-grade"><span class="badge nutri-a text-white">{{ product.nutrition_score.upper }}</span></div>
        {% elif product.nutrition_score == "b" %}
          <div class="nutri-grade"><span class="badge nutri-b text-white">{{ product.nutrition_score.upper }}</span></div>
        {% elif product.nutrition_score == "c" %}
          <div class="nutri-grade"><span class="badge nutri-c text-dark">{{ product.nutrition_score.upper }}</span></div>
        {% elif product.nutrition_score == "d" %}
          <div class="nutri-grade"><span class="badge nutri-d text-white">{{ product.nutrition_score.upper }}</span></div>
        {% elif product.nutrition_score == "e" %}
          <div class="nutri-grade"><span class="badge nutri-e text-white">{{ product.nutrition_score.upper }}</span></div>
        {% endif %}

          <div class="container vbottom p-3">
            <a href="">
              {% if product.img is none %}
                <img class="img-responsive" src="{% static 'purbeurre/img/logo_pur_beurre.png' %}" alt="{{ product.product_name }}">
              {% else %}
                <img class="img-responsive" src="{{ product.img }}" alt="{{ product.product_name }}">
              {% endif %}
            </a>
  
            <!-- display the name of the product -->
            <h4><a href="{% url 'purbeurre:product_detail' id_product=product.id_product %}">{{ product.product_name }}</a></h4>

            <div class="favs mt-2">
              <!-- pass product_id to the url, to use it in the view and push it to db -->
              {% if user.is_authenticated %}
              <form action="" method="post">
                {% csrf_token %}
                
                <input type="hidden" name="origin" value="{{query_prod}}"/>
                <input type="hidden" name="replacement" value="{{product.id_product}}"/>
                <button class="btn btn-danger"><i class="fa fa-heart" aria-hidden="true">&nbsp;Ajouter aux favoris</i></button>
              </form>
              {% endif %}
            </div>
           
          </div>
          
        </div>
        {% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div>{% endif %}
        {% endfor %}
    <!-- !!end display infos about product -->
    </div>
  </div>

  {% if paginate %}
  <div class="clearfix"></div>
  <div class="container center my-4">
      <nav aria-label="">
          <ul class="pagination pagination-sm flex-wrap justify-content-center" style="text-overflow: ellipsis;">
            {% if products.has_previous %}
                <li class="page-item"><a class="page-link" href="?query={{ query }}&page={{ products.previous_page_number }}" aria-label='Précédent'>&laquo;</a></li>
            {% endif %}

            {% for page in page_range %}
              {% if page %}
                {% ifequal page products.number %}
                  <li class="page-item active">
                    <span class="page-link">{{ page }}</span>
                  </li>
                {% else %}
                  <li class="page-item">
                    <a href="?query={{ query }}&page={{ page }}" class="page-link">{{ page }}</a>
                  </li>
                {% endifequal %}
              {% else %}
                <li class="page-item disabled"><span class="page-link">. . .</span></li>
              {% endif %}
              {% endfor %}
              {% if products.has_next %}
                <li class="page-item"><a class="page-link" href="?query={{ query }}&page={{ products.next_page_number }}" aria-label='suivant'>&raquo;</a></li>
            {% endif %}
          </ul>
      </nav>
  </div>

  {% endif %}

</div>
{% endif %}
</section>
{% endblock content %}

templates/purbeurre/sign_up.html
{% extends 'purbeurre/base.html'%}

{% block title%}{{ page_title }}{% endblock %}

{% block content %}

<!-- {% include 'purbeurre/header.html' with title=title img=img %}  -->

<section class="page-section bg-dark text-white">
    <div class="container">
        <div class="row main">
            <div class="main-center col-sm-12">
                <h4 class="text-center mb-5"> Créer un compte </h4>
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                        {{ field.label_tag }}{{ field }}
                            </div>
                        </div>
                        <div class="mx-auto text-center">
                            {% for error in field.errors %}
                                <p style="color: red">{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endfor %}
                    <div class="text-center mt-4">
                        <div class="form-group d-inline">
                           <button type="submit" class="btn btn-primary"> S'enregistrer </button>
                        </div>
                        <br>
                        <br>
                        <!-- <div class="text-center d-inline">
                            <a href="{% url 'users:login' %}"> <button  class="btn btn-primary" style="margin:10px;">  Se connecter </button></a>
                        </div> -->
                </form>
                <div class="text-center d-inline">
                    <small class="text-muted">
                        Déjà un compte ? <a class="ml-2" href="{% url 'users:login' %}">Connexion</a>
                    </small>
                </div>    
                      </div>
            </div>
        </div>
    </div>
</section>




{% endblock content %}